version: "3"
services:
  api:
    image: api_server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports: 
      - 4000:4000
    networks: 
      - mern-stack-net
  client:
    image: react_app
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks: 
      - mern-stack-net
networks:
  mern-stack-net:
    driver: bridge