name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Install-server-dependancies:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : npm ci

  Install-ui-dependancies:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : cd client
        - run : npm ci
        - run : cd ../

  Server-unit-tests:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : npm test

  UI-unit-tests:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : cd client
        - run : npm test
        - run : cd ../

  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}